spring:
  application:
    name: journalApp

  data:
    mongodb:
      uri: mongodb+srv://harilakhani2264:RIRia76ngGoA5f8X@cluster0.k841g.mongodb.net/JournalDB?retryWrites=true&w=majority&appName=Cluster0
      database: journalDB
      auto-index-creation: true

  main:
    allow-circular-references: true

#server:
#  port: 8081
#  servlet:
#    context-path: /journal