spring:
  application:
    name: journalApp

  data:
    mongodb:
      uri: mongodb+srv://harilakhani2264:RIRia76ngGoA5f8X@cluster0.k841g.mongodb.net/JournalDB?retryWrites=true&w=majority&appName=Cluster0
      database: journalDB
      auto-index-creation: true

  redis:
    uri: redis://default:QNbhfn0RPBVGzo91QQbIxaZKVQFuCfzI@redis-10421.c301.ap-south-1-1.ec2.redns.redis-cloud.com:10421

  main:
    allow-circular-references: true

#server:
#  port: 8081
#  servlet:
#    context-path: /journal