spring:
  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: harilakhani2264@gmail.com
    password: sojr jlya ircz lzly
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



weather:
  api:
    key: a9365e5641eed7a34457974b4c47546f

#weather_api_key: a9365e5641eed7a34457974b4c47546f



#logging:
#  level:
#    net:
#      example:
#        journalApp: DEBUG